### ISSUE TITLE
how to recover wallet?

### ISSUE THREAD

**Issue by petervnv** [HODLERTECH/HODLER-Android-Multi-Asset-Wallet#168]
Hi everyone,

I'm trying to regain access to the wallet I created years ago and need some help getting pointed in the right direction.

I believe I remember parts of the password I used at the time so I've created a script to test them out (essentially a worldlist to use as a dictionary in a bruteforce attack).

I have the recovery QRcode but would like to know how I can get access to the actual wallet file so I can try and bruteforce it with my list offline.

Any ideas?

Thanks

**Comment by anywalletrecovery** [comment]
@petervnv 
I have powerful machine to crack all  wallets from 2012-2022 and can recover many wallet password.
for fast response text me in telegram or gmail
Telegram: @walletrecover
anywalletrecovery@gmail.com

**Comment by UncipheredLLC** [comment]
Hi @petervnv,

We have new in house tools to open HOLDER Wallets 100% of the time. Please contact us at unlock@unciphered.com or visit our page and fill the form in here: https://www.unciphered.com/letsgo

We look forward to chatting shortly with you.

-Unciphered Team
